/* HC_M_FoodDao_insert.sql */
insert into hc_m_food(
  FOOD_NAME,
  SEARCH_WORDS,
  WYC_TYPE,
  MAINDISH_FLG,
  FOOD_TYPE,
  CARBO,
  PROT,
  FAT,
  VA,
  VB1,
  VB2,
  VC,
  FE,
  CA,
  FIB,
  SALT,
  FOOD_IMG,
  DEL_FLG,
  CREATE_AT,
  UPDATE_AT
)
VALUES (
    /*dto.foodName*/'ぽてとさらだ',
    /*dto.searchWords*/'[ぽてとさらだ][さらだ][やさい]',
    /*dto.wycType*/10,
    /*dto.maindishFlg*/0,
    /*dto.foodType*/'[10]',
    /*dto.carbo*/1,
    /*dto.prot*/1,
    /*dto.fat*/1,
    /*dto.va*/1,
    /*dto.vb1*/1,
    /*dto.vb2*/1,
    /*dto.vc*/1,
    /*dto.fe*/1,
    /*dto.ca*/1,
    /*dto.fib*/1,
    /*dto.salt*/1,
    /*dto.foodImg*/'',
    /*dto.delFlg*/0,
    /*dto.createAt*/'2019/08/06 22:30:40',
    /*dto.updateAt*/'2019/08/06 22:30:40'
);
